---

- name: docker apt key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: docker apt repo
  apt_repository:
    repo:  "deb https://apt.dockerproject.org/repo debian-jessie main"
    state: present

- name: Install packages
  package: name={{ item }} state=present
  with_items: 
   - docker-engine

- service: name=docker enabled=yes state=started

